/*
 * Filename: swc_engine.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component
 * name: swc_engine
 * shortname: engine
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_engine.h"



/* USER CODE START SWC_ENGINE_INCLUDE */
#include "stdlib.h"
/* USER CODE END SWC_ENGINE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */



/*
 * component: swc_engine
 * cycletime: 100
 * description: Runnable
 * events: 
 * name: ENGINE_setEngine_run
 * shortname: setEngine
 * signalIN: so_speed
 * signalOUT: so_engine
 * task: tsk_io
 */
void ENGINE_setEngine_run(RTE_event ev){
	
	/* USER CODE START ENGINE_setEngine_run */
    
    // UART Log fro verification
   /*
    UART_LOG_PutString("\n");
    char log[200];
    */
    SC_ENGINE_data_t engineSpd;
    SC_SPEED_data_t speed;
    static uint32_t age = 0;
    if(RTE_SC_SPEED_getStatus(&SO_SPEED_signal) == RTE_SIGNALSTATUS_VALID)
    {
        speed = RTE_SC_SPEED_get(&SO_SPEED_signal);
        age = RTE_SC_SPEED_getAge(&SO_SPEED_signal);
        if(age < 1000)
        {
            engineSpd.engine = speed.speed_val;

            //UART log for verification 
            //itoa(age, log, 10);
            //UART_LOG_PutString("Engine speed pos\n");
            //itoa(engineSpd.engine, log, 10);
            //UART_LOG_PutString(log);            
        }
        else
        {
            engineSpd.engine = 0;
            
            //itoa(age, log, 10);
            //UART log for verification  
            //UART_LOG_PutString("Engine speed zero\n");
            //itoa(engineSpd.engine, log, 10);
            //UART_LOG_PutString(log); 
        }
    }
    else
    {
        engineSpd.engine = 0;
    }
    RTE_SC_ENGINE_set(&SO_ENGINE_signal, engineSpd);
    RTE_SC_ENGINE_pushPort(&SO_ENGINE_signal);
    
    WD_Alive(2);
    
    /* USER CODE END ENGINE_setEngine_run */
}

/* USER CODE START SWC_ENGINE_FUNCTIONS */

/* USER CODE END SWC_ENGINE_FUNCTIONS */

