/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ErikaOS_1_ee.h"
#include "ErikaOS_1_ee_tracing.h"
#include "Joystick_YPos_aliases.h"
#include "Joystick_YPos.h"
#include "Joystick_XPos_aliases.h"
#include "Joystick_XPos.h"
#include "Joystick_ADC.h"
#include "PWM_Clock.h"
#include "RGB_PWM_green.h"
#include "RGB_G_aliases.h"
#include "RGB_G.h"
#include "LED_red_aliases.h"
#include "LED_red.h"
#include "UART_LOG.h"
#include "Joystick_ADC_SAR.h"
#include "Joystick_ADC_IntClock.h"
#include "Joystick_ADC_TempBuf_dma.h"
#include "Joystick_ADC_FinalBuf_dma.h"
#include "Joystick_ADC_IRQ.h"
#include "UART_LOG_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

